### ISSUE TITLE
Erro nas imagens da documentação

### ISSUE THREAD

**Issue by martinsglucas** [fga-eps-mds/2023-2-GEROcuidado-Doc#100]
### Descrição
As imagens colocadas na documentação das ferramentas estão dando erro no github pages e no arquivo .md

## Comportamento Atual
O erro aconteceu tanto com a tag `<img>` quanto com o `![]()` do markdown não funcionaram.  Foi passado o caminho das imagens, mas elas não aparecem

![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/104236229/a5ff9550-7bf1-46b2-a16f-8b5e0369b76f)
![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/104236229/caedf492-ca81-4a6a-8212-f8c03952a844)
![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/104236229/c64e03cd-8398-4ef9-81d9-7624951f4b4f)

## Comportamento Esperado
As imagens deveriam aparecer corretamente no github pages

![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/104236229/6ea057b8-dd4b-4ffc-bee9-999cc75b0e9b)

## Possível Solução
Colocar o caminho da imagem de outra forma

## Passos para Reproduzir
1. Acessar a página [https://fga-eps-mds.github.io/2023-2-GEROcuidado-Doc/planejamento/ferramentas/](https://fga-eps-mds.github.io/2023-2-GEROcuidado-Doc/planejamento/ferramentas/)

## Contexto
mkdocs rodado no GitHub Pages
### Tipo de Usuário
Qualquer

**Comment by EduardoGurgel** [comment]
Para corrigir esse erro, basta realizar o upload da imagem no github mesmo. Arrastando a imagem para um campo de comentário, por exemplo. E copiando o link de upload para dentro da tag no arquivo .md.

Link exemplo -> "https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/51385738/383f84e3-d606-467f-a39f-69c68f3b2239"

<div align = "center">
    <img src = "https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/51385738/383f84e3-d606-467f-a39f-69c68f3b2239" alt = "React Native Logo" width = "100" height = "100" style = "margin: 15">
</div>
