### ISSUE TITLE
[US-07] Adição da agenda/calendário

### ISSUE THREAD

**Issue by EduardoGurgel** [fga-eps-mds/2023-2-GEROcuidado-Doc#106]
### Descrição

Eu, como **Cuidador**, desejo **agendar** as rotina dos idosos em um calendário para que possa **organizar** as atividades, remédios e alimentos no dia a dia do idoso.

Criar um calendário para que seja possível organizar as rotinas assim como ser notificado sobre o mesmo.
### Pré-requisitos

- #88
- #112
- #114 

### Microsserviço
- [Microsserviço Saude](https://github.com/fga-eps-mds/2023-2-GEROcuidado-APISaude)

### Tarefas:

1. #202
2. #203

### Critérios de Aceitação
- [x] A rotina ao ser criada pelo cuidador/idoso autônomo, deve ser inserida corretamente na data e na hora correta.
- [x] O cuidador ter sucesso ao visualizar um dia em específico e suas rotinas associadas.
- [x] O cuidador/idoso autônomo pode visualizar as rotinas pela semana.

### Protótipo

![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/49076513/372c6c94-aa98-4fac-95a1-a39d7a3ab66b)

**Comment by hxnriqux** [comment]
Dúvida
- Não entendi muito bem a diferença dessa funcionalidade para a [US-04] CRUD de rotina #114

**Comment by EduardoGurgel** [comment]
Boa noite, @hxnriqux.
- A issue #114  está relacionada apenas com o cadastro de rotinas, já esta issue está relacionada ao **calendário** em si, também a listagem das rotinas quando selecionado o dia. Obrigado por comentar!

**Comment by capghafa** [comment]
Boa noite!
Seria possível visualizar as semanas anteriores ou futuras na página principal da agenda?

**Comment by EduardoGurgel** [comment]
@capghafa Boa tarde!
Será possível sim, estamos vendo a possibilidade de visualizar 100 dias atrás e 100 dias da data posterior.
