### ISSUE TITLE
[US-06] Criação das notificações

### ISSUE THREAD

**Issue by west7** [fga-eps-mds/2023-2-GEROcuidado-Doc#110]
### Descrição

Eu, como Usuário, desejo receber notificações do aplicativo para não esquecer de realizar minhas atividades cadastradas.

Nesta tarefa, ao cadastar uma atividade, o aplicativo deve notificar o usuário sobre horários e detalhes da atividade cadastrada. O usuário deve conseguir configurar as notificações afim de facilitar o gerenciamento de sua rotina e a interação com o aplicativo.

### Pré-requisitos
- #114 

### Microsserviço
- [Microsserviço saúde](https://github.com/fga-eps-mds/2023-2-GEROcuidado-APISaude)

### Tarefas:
1.  #199 
2. #200 

### Critérios de Aceitação
- [ ] O usuário conseguir cadastrar as notificações
- [ ] O usuário ser notificado com sucesso

### Protótipo

![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/101183849/ed9176e4-3572-4f18-8db1-2b613c75857f)

**Comment by hxnriqux** [comment]
Dúvida
- o usuário teria que cadastrar a notificação separadamente do CRUD de rotina ou essa tela seria apenas um gerenciamento das notificações?

**Comment by GustavoAPS** [comment]
> Dúvida
> 
>     * o usuário teria que cadastrar a notificação separadamente do CRUD de rotina ou essa tela seria apenas um gerenciamento das notificações?

De fato Henrique são feitas na mesma tela o CRUD de rotina e habilitar ou não as notifações, acabamos de atualizar o protótipo e a história, obrigado pela observação.
