### ISSUE TITLE
[US-02] CRUD de publicação do fórum

### ISSUE THREAD

**Issue by JulioR2022** [fga-eps-mds/2023-2-GEROcuidado-Doc#111]
## Descrição
Eu, como Cuidador/Idoso autônomo/Familiar, desejo fazer publicações no fórum, e ser capaz de apagar ou atualizar uma publicação realizada para que eu possa obter informações. 

Nesta tarefa o usuário deve ser capaz de criar, visualizar, editar e apagar publicações no fórum. De modo que, ele possa compartilhar experiências com outros usuários e visualizar outras postagens. 

### Pré-requisitos
- #88 

### Frontend
- [x] #160
- [x] #161
- [x] #153
- [x] #154
- [x] #156
- [x] #158

### Backend
- [x] #155
- [x] #157
- [x] #159 

## Critérios de Aceitação
- [x] Criar uma publicação e ela estar corretamente persistida no sistema.
- [x] Listar as publicações no fórum.
- [x] Busca correta de publicações por palavras-chave ou categorias associadas.
- [x] Apagar uma  publicação e ela não estar mais presente no fórum.
- [x] Editar uma publicação e as edições serem visíveis no fórum.

#### Usuário Cadastrado
![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/104236229/edc37ac7-f2fa-4184-ac90-10cb42c3b2b5)

#### Usuário Anônimo
![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/49076513/bdb2969d-eb09-46a2-8e9f-ed0af1cccac8)

**Comment by pedrobolt** [comment]
@EduardoGurgel boa tarde, por esse comentario voce ja conseguiria me dar acesso ao repositorio?

**Comment by EduardoGurgel** [comment]
> @EduardoGurgel boa tarde, por esse comentario voce ja conseguiria me dar acesso ao repositorio?

Boa tarde, consigo sim!
