### ISSUE TITLE
Padrões da comunidade

### ISSUE THREAD

**Issue by pedro-cella** [fga-eps-mds/2023-2-GEROcuidado-Doc#19]
# Descrição
Criação de um arquivo que explica sobre alguns padrões utilizados pela comunidade, como issues, README, pull requests, entre outros. 

# Tarefas
- [x] Criar documento de padrões da comunidade
- [ ] Adicionando código de conduta

# Critérios de Aceitação
- [x] Documento de padrões da comunidade estar disponível do gitpages

**Comment by EduardoGurgel** [comment]
Olá, Pedro.

Reabri a issue para adicionar os documentos de:
- [x] Código de conduta
- [x] Guia de contribuição
