### ISSUE TITLE
[Hotfix] apagar idoso

### ISSUE THREAD

**Issue by west7** [fga-eps-mds/2023-2-GEROcuidado-Doc#195]
### Descrição
O usuário não conseguia visualizar o botão de apagar idoso

## Comportamento Atual
O botão de apagar idoso não fica visível

## Comportamento Esperado
O botão deveria ser visível

## Possível Solução
Corrigir o estilo do botão na tela

## Passos para Reproduzir
1. Entrar na tela de editar idoso
2. Tentar apagar um idoso já cadastrado

## Contexto
O erro acontece porque alguns aparelhos não possuem tela de tamanho suficiente para exibir o botão

**Comment by pedro-cella** [comment]
Problema resolvido, a solução foi um ajuste no CSS da tela onde o botão Apagar Idoso se encontrava. Será verificado com os membros do Enactus se o problema persiste nos aparelhos deles
