### ISSUE TITLE
Treinamento

### ISSUE THREAD

**Issue by pedro-cella** [fga-eps-mds/2023-2-GEROcuidado-Doc#21]
# Descrição
Épico destinado as atividades de Treinamento voltado a capacitação do time de MDS nas tecnologias e metodologias do projeto.

# Atividades programadas
- [x] #27 
- [x] #28 
- [x] #29 
- [x] #46 
- [x] #47 
- [x] #48 
- [x] #49 
- [x] #50

**Comment by EduardoGurgel** [comment]
Treinamentos realizados!
- [x] #27 
- [x] #28 
- [x] #29 
- [x] #46 
- [x] #47 
- [x] #48 
- [x] #49
