### ISSUE TITLE
Treinamento de Linux

### ISSUE THREAD

**Issue by pedro-cella** [fga-eps-mds/2023-2-GEROcuidado-Doc#27]
# Descrição
Issue destinada a aplicação de treinamento de Linux aos MDS

# Tarefas
- [x] Realização da instalação do Linux;
- [x] Explicação sobre o terminal e outras funcionalidades e comandos;
- [x] Treinamento Aplicado;

# Critérios de Aceitação
- [x]  Treinamento devidamente aplicado

# Informações Adicionais
- Dia do treinamento: sexta-feira(15/09) 12-14h
- Local: FGA

**Comment by EduardoGurgel** [comment]
## Treinamento realizado!

![20230915_131924.jpg](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/51385738/983f20a6-5e28-485d-a1b8-c1949d1e685e)
