### ISSUE TITLE
Quadro de pareamento

### ISSUE THREAD

**Issue by pedro-cella** [fga-eps-mds/2023-2-GEROcuidado-Doc#39]
# Descrição
Desenvolver quadro de pareamento

# Tarefas
- [x] Criar quadro de pareamento;

# Critérios de Aceitação
- [x] Quadro de pareamento criado;
- [x] Quadro de pareamento adicionado no gitpages;

**Comment by EduardoGurgel** [comment]
Quadro de pareamento finalizado e disponibilizado no Gitpages [Quadro de pareamento](https://fga-eps-mds.github.io/2023-2-GEROcuidado-Doc/planejamento/quadro_pareamento/)

![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/51385738/bca75609-3b79-4118-9f14-6a86ece5617f)
