### ISSUE TITLE
Treinamento de SQL

### ISSUE THREAD

**Issue by pedro-cella** [fga-eps-mds/2023-2-GEROcuidado-Doc#49]
# Descrição
Issue destinada a aplicação do treinamento de SQL

# Tarefas
- [x] Treinamento aplicado

# Critérios de Aceitação
- [x] Treinamento devidamente aplicado

# Informações Adicionais

**Comment by EduardoGurgel** [comment]
# Treinamento realizado

## Link do treinamento:
https://youtu.be/BoHwt0wmkC8

## Exercícios de fixação
### 1 - Criar a tabela com os alunos de EPS e MDS (Disponível do Readme)

### 2 - Inserir os dados referentes aos alunos

### 3 - Adicionar a coluna notas e inserir notas para todos os alunos

### 4 - Ordenar a coluna do maior para o menor

### 5 - Remover as linhas em que as notas são menores que 5

**Comment by melohugo** [comment]
1- 
create table Alunos (
  Diciplina VARCHAR(3),
  Matricula INT PRIMARY KEY,
  Nome VARCHAR(255),
  GitHub VARCHAR(255)
  );
2-
INSERT INTO Alunos(Diciplina, Matricula, Nome, GitHub)
VALUES
	('EPS', 190054832,	'Arthur Talles de Sousa Cunha',	'Art1505'),
	('EPS',	190045485,	'Eduardo Gurgel Pereira de Carvalho',	'EduardoGurgel'),	
	('EPS',	170034992,	'Gustavo Afonso Pires Severo',	'GustavoAPS'),
	('EPS',	170144488,	'Henrique Amorim Costa Melo',	'HenriqueAmorim20'),
	('EPS',	170113060,	'Pedro Vítor de Salles Cella',	'pedro-cella'),
	('MDS',	221021984,	'Guilherme Silva Dutra',	'Thefast777'),
	('MDS',	211061805,	'Guilherme Westphall de Queiroz',	'west7'),
	('MDS',	221022570,	'Gabryel Nícolas Soares de Sousa',	'gabryelns'),
	('MDS',	221021993,	'Hugo Queiroz Camelo de Melo',	'melohugo'),
	('MDS',	221022041,	'Julio Roberto da Silva Neto',	'JulioR2022'),
	('MDS',	221022088,	'Lucas Martins Gabriel',	'W4RT1N5'),
	('MDS',	212005444,	'Pedro Fonseca Cruz',	'pfc15');

3-
ALTER TABLE Alunos
ADD nota INT;

UPDATE Alunos
SET Nota = 5
WHERE Diciplina = 'EPS';

UPDATE Alunos
SET Nota = 4
WHERE Diciplina = 'MDS'

4-
SELECT *
FROM Alunos

ORDER BY Nota ASC

5- 
DELETE FROM Alunos
WHERE  Nota < 5

**Comment by west7** [comment]
CREATE TABLE Alunos (
    MATRICULA INT PRIMARY KEY,
  	DISCIPLINA VARCHAR(3),
    NOME VARCHAR(200),
    GITHUB VARCHAR(100)
	);
 
INSERT INTO Alunos(disciplina, matricula, nome, github)
VALUES 
  ('MDS', 211061805, 'Guilherme Westphall de Queiroz', 'west7'),
  ('EPS',	190054832,	'Arthur Talles de Sousa Cunha',	'Art1505'),
  ('EPS',	190045485,	'Eduardo Gurgel Pereira de Carvalho',	'EduardoGurgel'),
  ('EPS',	170034992,	'Gustavo Afonso Pires Severo',	'GustavoAPS'),
  ('EPS',	170144488,	'Henrique Amorim Costa Melo',	'HenriqueAmorim20'),
  ('EPS',	170113060,	'Pedro Vítor de Salles, Cella',	'pedro-cella'),
  ('MDS',	221021984,	'Guilherme Silva Dutra',	'Thefast777'),
  ('MDS',	221022570,	'Gabryel Nícolas Soares de Sousa',	'gabryelns'),
  ('MDS',	221021993,	'Hugo Queiroz Camelo de Melo',	'melohugo'),
  ('MDS',	221022041,	'Julio Roberto da Silva Net',	'JulioR2022'),
  ('MDS',	221022088,	'Lucas Martins Gabriel',	'W4RT1N5'),
  ('MDS',	212005444,	'Pedro Fonseca Cruz',	'pfc15');

ALTER TABLE Alunos
ADD NOTAS INT;

UPDATE Alunos
SET NOTAS = 4
WHERE NOME Like 'G%';


UPDATE Alunos
set NOTAS = 7
WHERE NOTAS ISNULL;

SELECT *
FROM Alunos

ORDER BY NOTAS DESC;

DELETE FROM Alunos
WHERE NOTAS < 5;

SELECT *
FROM Alunos

**Comment by martinsglucas** [comment]
1. Criar a tabela com os alunos de EPS e MDS (Disponível do Readme)
```sql
create table integrantes (
disciplina varchar(3) not null,
matricula integer primary key,
nome varchar(100),
github varchar(20)
);
```
2. Inserir os dados referentes aos alunos
```sql
insert into integrantes (disciplina, matricula, nome, github)
values
('EPS', 190054832, 'Arthur Talles de Sousa Cunha', 'Art1505'),
('EPS', 190045485, 'Eduardo Gurgel Pereira de Carvalho', 'EduardoGurgel'),
('EPS', 170034992, 'Gustavo Afonso Pires Severo', 'GustavoAPS'),
('EPS', 170144488, 'Henrique Amorim Costa Melo', 'HenriqueAmorim20'),
('EPS', 170113060, 'Pedro Vítor de Salles Cella', 'pedro-cella'),
('MDS', 221021984, 'Guilherme Silva Dutra', 'Thefast777'),
('MDS', 211061805, 'Guilherme Westphall de Queiroz', 'west7'),
('MDS', 221022570, 'Gabryel Nícolas Soares de Sousa', 'gabryelns'),
('MDS', 221021993, 'Hugo Queiroz Camelo de Melo', 'melohugo'),
('MDS', 221022041, 'Julio Roberto da Silva Neto', 'JulioR2022'),
('MDS', 221022088, 'Lucas Martins Gabriel', 'W4RT1N5'),
('MDS', 212005444, 'Pedro Fonseca Cruz', 'pfc15');
```
3. Adicionar a coluna notas e inserir notas para todos os alunos
 ```sql
alter table integrantes
add nota int;
```
```sql
update integrantes
set nota = 5;
```
```sql
update integrantes
set nota = 7
where matricula like "%2";
```
```sql
update integrantes
set nota = 4
where matricula like "%8";
```
4. Ordenar a coluna do maior para o menor
```sql
select * from integrantes
order by nota desc;
``` 
5. Remover as linhas em que as notas são menores que 5
```sql
delete from integrantes
where nota < 5;
```

**Comment by JulioR2022** [comment]
------------------------------------- Questao1-----------------------------------------
CREATE TABLE Alunos(
MATRICULA INT PRIMARY KEY,
NOME VARCHAR(255),
CURSO VARCHAR(3),
USUARIO VARCHAR(255)
);

-----------------------------------Q2-------------------------------------------------------
INSERT INTO Alunos(CURSO,MATRICULA,NOME, USUARIO)
VALUES
('EPS', 190054832, 'Arthur Talles de Sousa Cunha', 'Art1505'),
('EPS', 190045485, 'Eduardo Gurgel Pereira de Carvalho', 'EduardoGurgel'),
('EPS', 170034992, 'Gustavo Afonso Pires Severo', 'GustavoAPS'),
('EPS', 170144488, 'Henrique Amorim Costa Melo', 'HenriqueAmorim20'),
('EPS', 170113060, 'Pedro Vítor de Salles Cella', 'pedro-cella'),
('MDS', 221021984, 'Guilherme Silva Dutra', 'Thefast777'),
('MDS', 211061805, 'Guilherme Westphall de Queiroz', 'west7'),
('MDS', 221022570, 'Gabryel Nícolas Soares de Sousa', 'gabryelns'),
('MDS', 221021993, 'Hugo Queiroz Camelo de Melo', 'melohugo'),
('MDS', 221022041, 'Julio Roberto da Silva Neto', 'JulioR2022'),
('MDS', 221022088, 'Lucas Martins Gabriel', 'W4RT1N5'),
('MDS', 212005444, 'Pedro Fonseca Cruz', 'pfc15');

-----------------------------------------------Q3----------------------------------------------

ALTER TABLE Alunos
ADD Nota INT;

UPDATE Alunos
Set Nota = 4
WHERE CURSO = 'MDS';

UPDATE Alunos
set Nota = 5
WHERE CURSO = 'EPS';

----------------------------------------------Q4-----------------------------------------------

SElECT *
FROM Alunos
ORDER BY NOTAS DESC;

--------------------------------------------Q5---------------------------------------------------

DELETE FROM Alunos
WHERE Nota < 5;

**Comment by GuiDutra21** [comment]
Questão 1 - 

CREATE TABLE Alunos
( 
  Disciplina VARCHAR(3),
  Matrícula INT PRIMARY KEY,
  Nome VARCHAR (70),
  GitHub VARCHAR (50)
);

questão 2 - 

INSERT INTO Alunos(disciplina, matrícula, nome, github)
Values	('EPS', 190054832, 'Arthur Talles de Sousa Cunha', 'Art1505'),
		('EPS', 190045485 , 'Eduardo Gurgel Pereira de Carvalho','EduardoGurgel'),
        ('EPS', 170034992, 'Gustavo Afonso Pires Severo', 'GustavoAPS'),
        ('EPS', 170144488, 'Henrique Amorim Costa Melo', 'HenriqueAmorim20'),
        ('EPS', 170113060, 'Pedro Vítor de Salles Cella', 'pedro-cella'),
        ('MDS', 221021984, 'Guilherme Silva Dutra','Thefast777'),
        ('MDS', 211061805, 'Guilherme Westphall de Queiroz', 'west7'),
        ('MDS', 221022570, 'Gabryel Nícolas Soares de Sousa', 'gabryelns'),
        ('MDS', 221021993, 'Hugo Queiroz Camelo de Melo', 'melohugo'),
        ('MDS', 221022041, 'Julio Roberto da Silva Neto', 'JulioR2022'),
        ('MDS', 221022088, 'Lucas Martins Gabriel', 'W4RT1N5'),
        ('MDS', 212005444, 'Pedro Fonseca Cruz', 'pfc15);

questão 3 - 

ALTER TABLE Alunos
ADD Notas int;

UPDATE Alunos
SET notas = 5
WHERE matrícula = 190054832;

UPDATE Alunos
SET notas = 7
WHERE matrícula = 190045485;

UPDATE Alunos
SET notas = 3
WHERE matrícula = 170034992;

UPDATE Alunos
SET notas = 6
WHERE matrícula = 170144488 ;

UPDATE Alunos
SET notas = 5
WHERE matrícula = 170113060;

UPDATE Alunos
SET notas = 4
WHERE matrícula = 221021984;

UPDATE Alunos
SET notas = 1
WHERE matrícula = 211061805;

UPDATE Alunos
SET notas = 9
WHERE matrícula = 221022570;

UPDATE Alunos
SET notas = 8
WHERE matrícula = 221021993;

UPDATE Alunos
SET notas = 4
WHERE matrícula = 221022041;

UPDATE Alunos
SET notas = 7
WHERE matrícula = 221022088;

UPDATE Alunos
SET notas = 6
WHERE matrícula = 212005444;

questão 4 -

SELECT* FROM ALUNOS
ORDER BY notas DESC


questão 5 -

Delete FROM Alunos
WHERE NOTAS < 5;

**Comment by gabryelns** [comment]
1 - Criar a tabela com os alunos de EPS e MDS (Disponível do Readme)

CREATE TABLE alunos (
           MATRICULA INT PRYMARY KEY,
           DISCIPLINA VARCHAR(3),
           NOME VARCHAR(255),
           USERGIT(255)
);

2 - Inserir os dados referentes aos alunos

INSERT INTO alunos(DISCIPLINA, MATRICULA, NOME, USERGIT)
VALUES 
('EPS', 190045485 , 'Eduardo Gurgel Pereira de Carvalho','EduardoGurgel'),
('EPS', 170034992, 'Gustavo Afonso Pires Severo', 'GustavoAPS'),
('EPS', 170144488, 'Henrique Amorim Costa Melo', 'HenriqueAmorim20'),
('EPS', 170113060, 'Pedro Vítor de Salles Cella', 'pedro-cella'),
('MDS', 221021984, 'Guilherme Silva Dutra','Thefast777'),
('MDS', 211061805, 'Guilherme Westphall de Queiroz', 'west7'),
('MDS', 221022570, 'Gabryel Nícolas Soares de Sousa', 'gabryelns'),
('MDS', 221021993, 'Hugo Queiroz Camelo de Melo', 'melohugo'),
('MDS', 221022041, 'Julio Roberto da Silva Neto', 'JulioR2022'),
('MDS', 221022088, 'Lucas Martins Gabriel', 'W4RT1N5'),
('MDS', 212005444, 'Pedro Fonseca Cruz', 'pfc15);

3 - Adicionar a coluna notas e inserir notas para todos os alunos

ALTER TABLE alunos 
ADD INT NOTAS;

UPDATE alunos
SET notas = 4
WHERE matrícula = 190054832;

UPDATE alunos
SET notas = 8
WHERE matrícula = 190045485;

UPDATE alunos
SET notas = 4
WHERE matrícula = 170034992;

UPDATE alunos
SET notas = 7
WHERE matrícula = 170144488 ;

UPDATE alunos
SET notas = 4
WHERE matrícula = 170113060;

UPDATE alunos
SET notas = 5
WHERE matrícula = 221021984;

UPDATE alunos
SET notas = 2
WHERE matrícula = 211061805;

UPDATE alunos
SET notas = 8
WHERE matrícula = 221022570;

UPDATE alunos
SET notas = 7
WHERE matrícula = 221021993;

UPDATE alunos
SET notas = 2
WHERE matrícula = 221022041;

UPDATE alunos
SET notas = 3
WHERE matrícula = 221022088;

UPDATE alunos
SET notas = 6
WHERE matrícula = 212005444;

4 - Ordenar a coluna do maior para o menor

SELECT * FROM alunos
ORDER BY alunos DESC;

5 - Remover as linhas em que as notas são menores que 5

DELETE FROM alunos
WHERE NOTAS < 5;
