### ISSUE TITLE
Atualização dos gráficos de Gantt do projeto

### ISSUE THREAD

**Issue by EduardoGurgel** [fga-eps-mds/2023-2-GEROcuidado-Doc#65]
# Descrição
Atualizar e manter atualizado os gráficos de Gantt referentes aos Épicos do projeto

# Tarefas
- [x] Manter atualizado os gráficos de gantt;

# Critérios de Aceitação
- [x] Gráficos de Gantt atualizados no Zenhub;

**Comment by pedro-cella** [comment]
Gráficos de Gantt atualizados no Roadmap

![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/49076513/49ea84db-2755-4fbb-a41d-a65d8dad741b)
