### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by EduardoGurgel** [fga-eps-mds/2023-2-GEROcuidado-Doc#68]
## Descrição
Criação do backlog do produto.

## Tarefas
- [x] Criação do backlog do produto;
- [x] Documentação do backlog do produto;
- [x] Adição do backlog ao Zenhub;

## Critérios de aceitação
- [x] Backlog do produto documentado;
- [x] Backlog do produto adicionado ao Zenhub;

**Comment by pedro-cella** [comment]
Backlog atualizado no Zenhub

![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/49076513/3aa4f0e1-5bbf-45fc-a661-6737c955c7bf)
